---
hostname: R1
ansible_host: 192.168.0.104
device_type: vios
need_dfgw: True
default_gateway: 192.168.0.1

ports: 
  interface1: 
    ip_address: 192.168.1.1 255.255.255.0
    acl_in: acl_ssh_looky
    acl_out:  acl_ssh_looky
  interface2: 
    ip_address: 192.168.13.1 255.255.255.0
  interface3: 
    ip_address: 192.168.15.1 255.255.255.0
  interface4: 
    ip_address: 192.168.0.3 255.255.255.0

acl_ssh_looky: True
acl_insecure: False